"use strict";
const userName = "Ajay";
const email = "ajay@gmail.com";
const isSubscribed = true;
let age = 22;
let city = "Ongole";
let loginCount = 5;
age = age + 1;
const profileMessage = `Hello ${userName}, you are ${age} years old and your email is ${email}`;
const isEligibleForPremium = age > 18 && isSubscribed;
const isAdult = age >= 18;
const hasHighLoginCount = loginCount > 3;
console.log("--- USER PROFILE DETAILS ---");
console.log("User Name:", userName);
console.log("Age:", age);
console.log("Email:", email);
console.log("Subscribed:", isSubscribed);
console.log("\n--- TYPE INFERENCE VALUES ---");
console.log("City:", city);
console.log("Login Count:", loginCount);
console.log("\n--- PROFILE MESSAGE ---");
console.log(profileMessage);
console.log("\n--- CONDITIONS ---");
console.log("Is Adult:", isAdult);
console.log("Has High Login Count:", hasHighLoginCount);
console.log("Eligible for Premium:", isEligibleForPremium);
